################################ Dutch Language ########################
[nl]
contentDir = "content/nl"
languageName = "Nederlands"
languageCode = "nl-NL"
weight = 1

################# English language ################
[en]
contentDir = "content/en"
languageName = "English"
languageCode = "en-US"
weight = 2
