[[main]]
  name = "Services"
  URL = "/en/services/"
  weight = 1

[[main]]
  name = "Blog"
  URL = "/en/blog/"
  weight = 2

[[main]]
  name = "About me"
  URL = "/en/about/"
  weight = 3

[[main]]
  name = "Contact"
  URL = "/en/contact/"
  weight = 4

[[footer]]
  name = "Services"
  URL = "/en/services/"
  weight = 1

[[footer]]
  name = "Blog"
  URL = "/en/blog/"
  weight = 2

[[footer]]
  name = "About me"
  URL = "/en/about/"
  weight = 3

[[footer]]
  name = "Terms and Conditions"
  URL = "/en/terms-conditions/"
  weight = 4

[[footer]]
  name = "Contact"
  URL = "/en/services/"
  weight = 5
