[[main]]
  name = "Services"
  URL = "/products/"
  weight = 1

[[main]]
  name = "Blog"
  URL = "/blog/"
  weight = 2

[[main]]
  name = "Wie ben ik"
  URL = "/about/"
  weight = 3

[[main]]
  name = "Contact"
  URL = "/contact/"
  weight = 4

[[footer]]
  name = "Services"
  URL = "/products/"
  weight = 1

[[footer]]
  name = "Blog"
  URL = "/blog/"
  weight = 2

[[footer]]
  name = "Wie ben ik"
  URL = "/about/"
  weight = 3

[[footer]]
  name = "Algemene Voorwaarden"
  URL = "/terms-conditions/"
  weight = 4

[[footer]]
  name = "Contact"
  URL = "/contact/"
  weight = 5
