[[main]]
  name = "Services"
  URL = "/nl/products/"
  weight = 1

[[main]]
  name = "Blog"
  URL = "/nl/blog/"
  weight = 2

[[main]]
  name = "Wie ben ik"
  URL = "/nl/about/"
  weight = 3

[[main]]
  name = "Contact"
  URL = "/nl/contact/"
  weight = 4

[[footer]]
  name = "Services"
  URL = "/nl/products/"
  weight = 1

[[footer]]
  name = "Blog"
  URL = "/nl/blog/"
  weight = 2

[[footer]]
  name = "Wie ben ik"
  URL = "/nl/about/"
  weight = 3

[[footer]]
  name = "Algemene Voorwaarden"
  URL = "/nl/terms-conditions/"
  weight = 4

[[footer]]
  name = "Contact"
  URL = "/nl/contact/"
  weight = 5
