[[main]]
  name = "Services"
  URL = "/en/products/"
  weight = 1

[[main]]
  name = "Blog"
  URL = "/en/blog/"
  weight = 2

[[main]]
  name = "FAQ"
  URL = "/en/faq/"
  weight = 3

[[main]]
  name = "Contact"
  URL = "/en/contact/"
  weight = 4

[[footer]]
  name = "Services"
  URL = "/en/products/"
  weight = 1

[[footer]]
  name = "Blog"
  URL = "/en/blog/"
  weight = 2

[[footer]]
  name = "FAQ"
  URL = "/en/faq/"
  weight = 3

[[footer]]
  name = "Terms and Conditions"
  URL = "/en/terms-conditions/"
  weight = 4

[[footer]]
  name = "Contact"
  URL = "/en/contact/"
  weight = 5
