logo = "images/logo.png"
home = "Home"
description = "This is meta description"
author = "zenari.nl"
mobile = ""
email = "aleksandra@vraagdetandartsonline.nl"
location = "Alkmaar, The Nederlands"
copyright = ""
snipcartApiKey = ""
stripeApiKey = ""
currencySymbol = "€"

[preloader]
enable = true
preloader = ""

[rating]
enable = true
websiteID = "444334"
publicKey = "811cf0927332bf51f2e12f84608594ac"

[[social]]
icon = "ti-facebook"
link = "#"

[[social]]
icon = "ti-twitter-alt"
link = "#"

[[social]]
icon = "ti-instagram"
link = "#"

[[social]]
icon = "ti-youtube"
link = "#"

# Contact Form
[contact]
formAction = "https://formspree.io/f/myzzyyqa" # contact form works with formspree.io

############################# Plugins ##############################
[plugins]

  # CSS Plugins
  [[plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[plugins.css]]
  link = "plugins/slick/slick.css"
  [[plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[plugins.js]]
  link = "plugins/google-map/gmap.js"
