[build]
  publish = "public"
  command = "hugo --gc --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.115.1"
  HUGO_BASEURL = "/"
  HUGO_THEME = "hargo-hugo"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"